[tool.black]
target-version = [ "py39" ]

[tool.ruff]
fix = true

lint.select = [
  "C4",     # flake8-comprehensions
  "E",      # pycodestyle errors
  "F",      # pyflakes errors
  "I",      # isort
  "ISC",    # flake8-implicit-str-concat
  "LOG",    # flake8-logging
  "PGH",    # pygrep-hooks
  "RUF100", # unused noqa (yesqa)
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
  "YTT",    # flake8-2020
]
lint.ignore = [
  "E203", # Whitespace before ':'
  "E221", # Multiple spaces before operator
  "E226", # Missing whitespace around arithmetic operator
  "E241", # Multiple spaces after ','
  "E501", # Line too long
]

[tool.mypy]
python_version = "3.12"
pretty = true
strict = true

# Extra checks that aren't included in --strict
enable_error_code = "ignore-without-code,redundant-expr,truthy-iterable"
extra_checks = true
warn_unreachable = true

exclude = [
  "^tests/test_release_tag.py$",
  "^tests/test_run_release.py$",
  "^tests/test_sbom.py$",
  "^windows-release/purge.py$",
]
